execute 'source' fnamemodify(expand('<sfile>'), ':h').'/general.vim'
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/plugins.vim'
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/themes.vim'
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/options.vim'
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/keymap.vim'
